---
- name: Create akash.txt file
  hosts: all
  become: yes
  become_user: root
  become: yes
  become_user: aka
  tasks:
    - name: Create akash.txt file
      ansible.builtin.file:
        path: /root/akash.txt
        path: /home/aka/akash.txt
        state: touch
...