---
- name: Create akash.txt file
  hosts: all
  become: yes
  become_user: root,kk
  tasks:
    - name: Create akash.txt file
      ansible.builtin.file:
        path: /root/akash.txt
        state: touch
...