---
- name: variable
  hosts: all
  become: yes
  vars:
    package_manager: "apt"
    apache_package: "apache2"  
  tasks:
    - name: installing package
        action:
        module: ansible.builtin.package
        name: "{{ apache_package }}"
        state: present


